language: php

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

php:
  - 7.1

before_script:
  - composer install -n --dev --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=tests/bootstrap.php src tests
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
