language: php

addons:
  chrome: beta

before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"

php:
  - 7.1

before_script:
  - composer install -n --dev --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=tests/bootstrap.php src tests
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
